version: '2'
services:
  namesrv:  
    image: going/rocketmq-namesrv:4.3.0
    ports:
      - 9876:9876
    volumes:
      - "E:/rocketmq/namesrv/master/logs:/opt/logs"
      - "E:/rocketmq/namesrv/master/store:/opt/store"
  broker:
    image: going/rocketmq-broker:4.2.0
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - "E:/rocketmq/broker/master-1/logs:/opt/logs"
      - "E:/rocketmq/broker/master-1/store:/opt/store"
    links:
      - namesrv:namesrv
  console:
    image: styletang/rocketmq-console-ng:latest
    ports:
     - "8080:8080"
    links:
     - namesrv:namesrv
    environment:
     JAVA_OPTS: -Drocketmq.config.namesrvAddr=namesrv:9876 #-Dcom.rocketmq.sendMessageWithVIPChannel=false
xxx